version: "3"

services:
  user_db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    volumes:
      - user_db_data:/var/lib/postgresql/data
      - ./database/user_db_init.sql:/docker-entrypoint-initdb.d/user_db_init.sql
    networks:
      - user_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  data_db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flights
    volumes:
      - data_db_data:/var/lib/postgresql/data    
      - ./database/data_db_init.sql:/docker-entrypoint-initdb.d/data_db_init.sql
    networks:
      - data_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  user_manager:
    build: ./user_manager
    networks:
      - user_network
      - shared_network
    ports:
      - "5000:5000"
      - "50051:50051"
    depends_on:
      user_db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:5000/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  data_collector:
    build: ./data_collector
    networks:
      - data_network
      - shared_network
      - kafka_network
    ports:
      - "5001:5001"
    depends_on:
    - data_db
    - user_manager
    environment:
      DATA_DB_HOST: ${DATA_DB_HOST}
      DATA_DB_PORT: ${DATA_DB_PORT}
      DATA_DB_NAME: ${DATA_DB_NAME}
      DATA_DB_USER: ${DATA_DB_USER}
      DATA_DB_PASSWORD: ${DATA_DB_PASSWORD}
      USER_MANAGER_HOST: ${USER_MANAGER_HOST}
      USER_MANAGER_GRPC_PORT: ${USER_MANAGER_GRPC_PORT}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: to-alert-system
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:5001/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
  alert_system:
    build: ./alert_system
    networks:
      - kafka_network
      - shared_network
      - data_network
    depends_on:
      - data_db
      - data_collector
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_ALERT_TOPIC: to-alert-system
      KAFKA_NOTIFIER_TOPIC: to-notifier
      DATA_DB_HOST: ${DATA_DB_HOST}
      DATA_DB_PORT: ${DATA_DB_PORT}
      DATA_DB_NAME: ${DATA_DB_NAME}
      DATA_DB_USER: ${DATA_DB_USER}
      DATA_DB_PASSWORD: ${DATA_DB_PASSWORD}
  alert_notifier:
    build: ./alert_notifier
    networks:
      - kafka_network
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_NOTIFIER_TOPIC: to-notifier

      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_USE_TLS: "true"


  api_gateway:
    build: ./infra/nginx
    container_name: api_gateway
    ports:
      - "8080:80"
    networks:
      - shared_network
    depends_on:
      - user_manager
      - data_collector
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/health || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    networks:
      - user_network
      - data_network
      - shared_network

networks:
  user_network:
  data_network:
  shared_network:
  kafka_network:
    external: true

volumes:
  user_db_data:
  data_db_data: