version: "3"

services:
  user_db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    volumes:
      - ./database/user_db_init.sql:/docker-entrypoint-initdb.d/user_db_init.sql
    networks:
      - user_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  data_db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flights
    volumes:
      - ./database/data_db_init.sql:/docker-entrypoint-initdb.d/data_db_init.sql
    networks:
      - data_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  user_manager:
    build: ./user_manager
    networks:
      - user_network
      - shared_network
    ports:
      - "5000:5000"
      - "50051:50051"
    depends_on:
      user_db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:5000/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  data_collector:
    build: ./data_collector
    networks:
      - data_network
      - shared_network
    ports:
      - "5001:5001"
    depends_on:
    - data_db
    - user_manager
    environment:
      DATA_DB_HOST: ${DATA_DB_HOST}
      DATA_DB_PORT: ${DATA_DB_PORT}
      DATA_DB_NAME: ${DATA_DB_NAME}
      DATA_DB_USER: ${DATA_DB_USER}
      DATA_DB_PASSWORD: ${DATA_DB_PASSWORD}
      USER_MANAGER_HOST: ${USER_MANAGER_HOST}
      USER_MANAGER_GRPC_PORT: ${USER_MANAGER_GRPC_PORT}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:5001/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5


  adminer:
    image: adminer
    ports:
      - "8081:8080"
    networks:
      - user_network
      - data_network
      - shared_network

networks:
  user_network:
  data_network:
  shared_network: