events {
    worker_connections 1024;
}

http {

  limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;
    
  upstream user_manager {
    server user_manager:5000;
  }

  upstream data_collector {
    server data_collector:5001;
  }

  server {
    listen 80;

    # Health del gateway
    location /health {
      return 200 "ok\n";
      add_header Content-Type text/plain;
    }

    # USER MANAGER API
    location /users/ {
      proxy_pass http://user_manager/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # DATA COLLECTOR API
    location /collector/ {
      proxy_pass http://data_collector/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}

