apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: dsbd-ns
data:
  # --- DATA DB (Postgres flights) ---
  DATA_DB_HOST: "data-db"
  DATA_DB_PORT: "5432"
  DATA_DB_NAME: "flights"
  DATA_DB_USER: "postgres"

  USER_MANAGER_HOST: "user-manager"
  USER_MANAGER_GRPC_PORT: "50051"

  # --- Kafka ---
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  KAFKA_ALERT_TOPIC: "to-alert-system"
  KAFKA_NOTIFIER_TOPIC: "to-notifier"
  KAFKA_TOPIC: "to-alert-system"

  # --- OpenSky ---
  CLIENT_ID: "rvsgpp99h28c351r@studium.unict.it-api-client"

  # --- SMTP ---
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "example@gmail.com"
  SMTP_FROM: "example@gmail.com"
  SMTP_USE_TLS: "true"

  # --- Postgres DB names ---
  POSTGRES_DB_USER: "users"
  POSTGRES_DB_DATA: "flights"
